// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YFFeAOc1wbj6WkpIkCd1xBVEb38AgVw',
    appId: '1:294602659204:web:33fdf588b4c7320b67f9d1',
    messagingSenderId: '294602659204',
    projectId: 'fir-postman-fe350',
    authDomain: 'fir-postman-fe350.firebaseapp.com',
    storageBucket: 'fir-postman-fe350.firebasestorage.app',
    measurementId: 'G-VZ61Q1C590',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJE_RDmkdmBptZhHH6DDJm5iSnQomxrQY',
    appId: '1:294602659204:android:b3d819ec31d70bed67f9d1',
    messagingSenderId: '294602659204',
    projectId: 'fir-postman-fe350',
    storageBucket: 'fir-postman-fe350.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4YFFeAOc1wbj6WkpIkCd1xBVEb38AgVw',
    appId: '1:294602659204:web:de518e6fb4c1ad0b67f9d1',
    messagingSenderId: '294602659204',
    projectId: 'fir-postman-fe350',
    authDomain: 'fir-postman-fe350.firebaseapp.com',
    storageBucket: 'fir-postman-fe350.firebasestorage.app',
    measurementId: 'G-JQ9DRZ9DGT',
  );
}
